<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Check.cs" Link="Check.cs" />
    <Using Include="Rifles.Checks" />
    <ProjectReference Include="../../src/Rifles.Procgen/Rifles.Procgen.csproj" />
  </ItemGroup>
</Project>
