using Rifles.Game.Magic;
using Rifles.Game.Items;
using Rifles.Game.Combat;
using Rifles.Game.Characters;
using Rifles.Game.Dungeon;
using Rifles.Game.Content;
using Rifles.Game.Party;
using Rifles.Game.Tests;
using Rifles.Procgen.Generation;
using Rusty.Engine.Entities;
using Rusty.Engine.Mechanics;

string contentRoot = Path.GetFullPath("content");
byte[] ReadContent(string path) => File.ReadAllBytes(Path.Combine(contentRoot, path));
GameDefinitions company = GameDefinitions.Load(path => path == "definitions/company-experiment.json" ? "{\"enabled\":true}"u8.ToArray() : ReadContent(path));
GameDefinitions definitions = GameDefinitions.Load(path => path == "definitions/company-experiment.json" ? "{\"enabled\":false}"u8.ToArray() : ReadContent(path));
Check.Run("CompanyChecks", () => CompanyChecks.Run(company));
Check.Run("CompanyBootstrapAndSaveChecks", () => BootstrapAndSaveChecks.Run(company, contentRoot));
if (args.Contains("--company-only", StringComparer.Ordinal)) return Check.Finish();
Check.Run("ExpeditionChecks", () => ExpeditionChecks.Run(definitions));
Check.Run("RoomCatalogueChecks", () => RoomCatalogueChecks.Run(definitions));
Check.Run("GeneratedFeatureChecks", () => GeneratedFeatureChecks.Run(definitions));
Check.Run("EncounterPlacementChecks", () => EncounterPlacementChecks.Run(definitions));
Check.Run("ArchitectureDetailChecks", () => ArchitectureDetailChecks.Run(definitions));
Check.Run("DressingPlacementChecks", () => DressingPlacementChecks.Run(definitions));
Check.Run("ActionChecks", () => ActionChecks.Run());
Check.Run("MagicChecks", () => MagicChecks.Run(definitions));
Check.Run("CommandChecks", () => CommandChecks.Run());
Check.Run("EnemyBrainChecks", () => EnemyBrainChecks.Run());
Check.Run("CrowdChecks", () => CrowdChecks.Run());
Check.Run("CrowdLaneChecks", () => CrowdLaneChecks.Run(definitions));
Check.Run("FormationRulesChecks", () => FormationRulesChecks.Run(definitions));
Check.Run("CommanderChecks", () => CommanderChecks.Run(definitions));
Check.Run("WeaponChecks", () => WeaponChecks.Run(definitions));
Check.Run("MusketChecks", () => MusketChecks.Run(definitions));
Check.Run("ChargeChecks", () => ChargeChecks.Run(definitions));
Check.Run("MartialDrillChecks", () => MartialDrillChecks.Run(definitions));
Check.Run("OrderChecks", () => OrderChecks.Run(definitions));
Check.Run("AbilityOrderChecks", () => AbilityOrderChecks.Run(definitions));
Check.Run("FormationPlannerChecks", () => FormationPlannerChecks.Run(definitions));
Check.Run("CombatInventoryChecks", () => CombatInventoryChecks.Run(definitions));
Check.Run("CombatSaveChecks", () => CombatSaveChecks.Run(definitions));
Check.Run("InventoryChecks", () => InventoryChecks.Run(definitions));
Check.Run("BootstrapAndSaveChecks", () => BootstrapAndSaveChecks.Run(definitions, contentRoot));
Check.Run("ProjectionAndFactoryChecks", () => ProjectionAndFactoryChecks.Run(definitions));
Check.Run("SaveEnumChecks", ProjectionAndFactoryChecks.SaveEnums);
Check.Run("ContentChecks", () => ContentChecks.Run(contentRoot));
return Check.Finish();
